name: 'Azure Pipelines'

trigger:
  batch: false
  branches:
    include:
    - master
pr:
  autoCancel: false
  branches:
    include:
    - master

variables:
  DOTNET_NOLOGO: true
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
  DOTNET_CLI_TELEMETRY_OPTOUT: true
  Image_Name: 'ubuntu-20.04'
  Build_Configuration: 'Release'

jobs:
# Unit Tests
- template: templates/unit-tests.yml
  parameters:
    imageName: ${{ variables.Image_Name }}
# Code Coverage
- template: templates/code-coverage.yml
  parameters:
    imageName: ${{ variables.Image_Name }}
# Mutation Testing
- template: templates/mutation-testing.yml
  parameters:
    imageName: ${{ variables.Image_Name }}
