name: 'Mutation Testing'

trigger:
  branches:
    include:
    - master
pr:
  branches:
    include:
    - master

variables:
  DOTNET_NOLOGO: true
  DOTNET_CLI_TELEMETRY_OPTOUT: true

jobs:
- job: 'mutation_testing'
  strategy:
    matrix:
      windows:
        imageName: 'windows-2019'
  pool:
    vmImage: $(imageName)

  variables:
    Solution_File: './source/F0.Analyzers.sln'
    Test_Project_Directory: './source/test/F0.Analyzers.Tests'
    NuGet_Configuration_File: './source/nuget.config'
    Stryker_Configuration_File: '../stryker-config.json'
    Stryker_Reporters: "'html', 'cleartext'"

  steps:
  # Init
  - checkout: self
    displayName: 'Checkout'
    fetchDepth: 1
  - task: UseDotNet@2
    displayName: 'Setup .NET Core SDK'
    inputs:
      packageType: 'sdk'
      useGlobalJson: true
      performMultiLevelLookup: true
  # Restore
  - task: DotNetCoreCLI@2
    displayName: 'Restore Dependencies'
    inputs:
      command: 'restore'
      restoreArguments: '$(Solution_File)'
      feedsToUse: 'config'
      nugetConfigPath: '$(NuGet_Configuration_File)'
      verbosityRestore: 'Minimal'
  - task: DotNetCoreCLI@2
    displayName: 'Install .NET Tools'
    inputs:
      command: 'custom'
      custom: 'tool'
      arguments: 'restore --configfile $(NuGet_Configuration_File)'
  # Mutate
  - task: DotNetCoreCLI@2
    displayName: 'Mutate Project'
    inputs:
      command: 'custom'
      custom: 'tool'
      arguments: 'run dotnet-stryker --config-file-path $(Stryker_Configuration_File) --reporters "[$(Stryker_Reporters)]"'
      workingDirectory: '$(Test_Project_Directory)'
  # Publish
  - task: PublishMutationReport@0
    displayName: 'Publish Mutation Test Report'
    inputs:
      reportPattern: '**/mutation-report.html'
