parameters:
- name: imageName
  displayName: 'Agent'
  type: string
  default: 'windows-latest'

jobs:
- job: 'mutation_testing'
  displayName: 'Mutation Testing'
  pool:
    vmImage: ${{ parameters.imageName }}

  variables:
    NuGet_Configuration_File: '$(System.DefaultWorkingDirectory)/nuget.config'
    Tool_Manifest_File: '$(System.DefaultWorkingDirectory)/.config/dotnet-tools.json'
    Test_Project_Directory: '$(System.DefaultWorkingDirectory)/source/test/F0.Analyzers.Tests'
    Stryker_Configuration_File: '$(System.DefaultWorkingDirectory)/source/test/stryker-config.json'

  steps:
  # Init
  - checkout: self
    displayName: 'Checkout'
    fetchDepth: 1
  - task: UseDotNet@2
    displayName: 'Setup .NET SDK'
    inputs:
      packageType: 'sdk'
      useGlobalJson: true
      performMultiLevelLookup: true
  # Restore
  - task: DotNetCoreCLI@2
    displayName: 'Install .NET Tools'
    inputs:
      command: 'custom'
      custom: 'tool'
      arguments: 'restore --configfile $(NuGet_Configuration_File) --tool-manifest $(Tool_Manifest_File) --no-cache'
  # Mutate
  - task: DotNetCoreCLI@2
    displayName: 'Mutate Project'
    inputs:
      command: 'custom'
      custom: 'tool'
      arguments: 'run dotnet-stryker --config-file-path $(Stryker_Configuration_File)'
      workingDirectory: '$(Test_Project_Directory)'
  # Publish
  - task: PublishMutationReport@0
    displayName: 'Publish Mutation Test Report'
    inputs:
      reportPattern: '**/mutation-report.html'
