parameters:
- name: imageName
  displayName: 'Agent'
  type: string
  default: 'windows-latest'

jobs:
- job: 'unit_tests'
  displayName: 'Unit Tests'
  pool:
    vmImage: ${{ parameters.imageName }}

  variables:
    Solution_File: '$(System.DefaultWorkingDirectory)/source/F0.Analyzers.Core.slnf'
    NuGet_Configuration_File: '$(System.DefaultWorkingDirectory)/nuget.config'

  steps:
  # Init
  - checkout: self
    displayName: 'Checkout'
    fetchDepth: 1
  - task: UseDotNet@2
    displayName: 'Setup .NET SDK'
    inputs:
      packageType: 'sdk'
      useGlobalJson: true
      performMultiLevelLookup: true
  # Restore
  - task: DotNetCoreCLI@2
    displayName: 'Restore Dependencies'
    inputs:
      command: 'restore'
      restoreArguments: '$(Solution_File)'
      feedsToUse: 'config'
      nugetConfigPath: '$(NuGet_Configuration_File)'
      verbosityRestore: 'Minimal'
  # Build
  - task: DotNetCoreCLI@2
    displayName: 'Build Projects'
    inputs:
      command: 'build'
      arguments: '$(Solution_File) --no-restore --nologo'
  # Test
  - task: DotNetCoreCLI@2
    displayName: 'Execute Unit Tests'
    inputs:
      command: 'test'
      arguments: '$(Solution_File) --logger trx --no-build --nologo'
      publishTestResults: false
  # Publish
  - task: PublishTestResults@2
    displayName: 'Publish Test Results'
    inputs:
      testResultsFormat: 'VSTest'
      testResultsFiles: '**/*.trx'
      mergeTestResults: true
      failTaskOnFailedTests: false
