name: Build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  Solution_File: ./source/F0.Analyzers.sln
  Solution_Core_File: ./source/F0.Analyzers.Core.slnf
  NuGet_Configuration_File: ./source/nuget.config
  Build_Configuration: Release

jobs:
  build:
    name: Build on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu-18.04, windows-2019, macos-10.15 ]

    steps:
    - name: Checkout
      uses: actions/checkout@v2.3.3
    - name: Restore
      run: dotnet restore $Solution_File --configfile $NuGet_Configuration_File
    - name: Build $Build_Configuration configuration
      run: dotnet build $Solution_Core_File --configuration $Build_Configuration --no-restore
