name: Build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    name: Build on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu-18.04, windows-2019, macos-10.15 ]

    env:
      Solution_File: ./source/F0.Analyzers.sln
      Solution_Core_File: ./source/F0.Analyzers.Core.Unix.slnf # https://github.com/dotnet/msbuild/issues/5715
      NuGet_Configuration_File: ./source/nuget.config
      Build_Configuration: Release

    steps:
    - name: Checkout
      uses: actions/checkout@v2.3.3
    - name: Restore
      run: dotnet restore ${{ env.Solution_File }} --configfile ${{ env.NuGet_Configuration_File }}
    - name: Build ${{ env.Build_Configuration }} configuration
      run: dotnet build ${{ env.Solution_Core_File }} --configuration ${{ env.Build_Configuration }} --no-restore
