name: Build VSIX

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    name: Build on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ windows-2022 ]
        configuration: [ Release ]

    env:
      Solution_Vsix_File: ./source/F0.Analyzers.Vsix.slnf

    steps:
    # Init
    - name: Checkout
      uses: actions/checkout@v4.0.0
      with:
        fetch-depth: 1
        show-progress: false
    - name: Setup MSBuild.exe (add msbuild to PATH)
      uses: microsoft/setup-msbuild@v1.3.1
      with:
        vs-version: '[17.0,18.0)'
        vs-prerelease: false
        msbuild-architecture: x64
    # Restore
    - name: Restore ${{ matrix.configuration }}
      run: msbuild ${{ env.Solution_Vsix_File }} /t:Restore /p:Configuration=${{ matrix.configuration }} -nologo
    # Build
    - name: Build ${{ matrix.configuration }}
      run: msbuild ${{ env.Solution_Vsix_File }} /p:Configuration=${{ matrix.configuration }} /p:DeployExtension=false -nologo
