name: Test Package

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  DOTNET_NOLOGO: true
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
  DOTNET_CLI_TELEMETRY_OPTOUT: true

jobs:
  test:
    name: Test on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu-22.04, windows-2022, macos-12 ]
        configuration: [ Release ]

    env:
      Solution_File: ./source/F0.Analyzers.sln
      Solution_Core_File: ./source/F0.Analyzers.Core.slnf
      NuGet_Configuration_File: ./nuget.config

    steps:
    # Init
    - name: Checkout
      uses: actions/checkout@v4.0.0
      with:
        fetch-depth: 1
        show-progress: false
    - name: Setup .NET SDK
      uses: actions/setup-dotnet@v3.2.0
      with:
        global-json-file: global.json
    # Restore
    - name: Restore
      run: dotnet restore ${{ env.Solution_File }} --configfile ${{ env.NuGet_Configuration_File }}
    # Build
    - name: Build ${{ matrix.configuration }}
      run: dotnet build ${{ env.Solution_Core_File }} --configuration ${{ matrix.configuration }} --no-restore --nologo
    # Test
    - name: Test ${{ matrix.configuration }}
      run: dotnet test ${{ env.Solution_Core_File }} --configuration ${{ matrix.configuration }} --no-build --nologo
